vars:
  exp_name: attantionalBlink
  total_trial_number: 240 # multiples of 32 work only
  T2_lag: 
    - 1
    - 3
    - 5
    - 7
  practice_length: 12
  part_keys: 
    - c
    - m
  monitor_size:
    - 1920
    - 1080
  backgr_color: 
    - 0
    - 0
    - 0
  text_color: 
    - -1
    - -1
    - -1
  target_color: 
    - 1
    - 1
    - 1
  units: pix
  wrapWidth: 1690
  textHeight: 40
  ITI: 4 
  fix: 11
  letter_time: 2
  betu_meret: 60
  targets: 
    - S
    - D
    - F
    - G
    - H
    - J
    - K
    - L
  letters:
    - Q
    - W
    - E
    - R
    - T
    - Z
    - U
    - I
    - O
    - P
    - A
    - S
    - D
    - F
    - G
    - H
    - J
    - K
    - L
    - Y
    - C
    - V
    - B
    - N
    - M


inst:
  start_exp: |
    In each trial you will see a stream of letters in the middle of the screen. Each letter will be presented for a very short time.

    Your task consists of two parts. First, you have to indicate which letter was presented in white (the options are: {}, {}, {}, {}, {}, {}, {}, {}). 
    Second, you have to indicate whether you saw an X in the stream (if there is an X it is always after the white letter)!
    There will be a 1 minute break in the middle.

    Try to be as accurate as possible!

    Press Space if you are ready to start!
  break: There is a 1 minute break now.
  press_space: Press Space to continue!
  identification: What letter did you see in white?
  detection: |
    Did you see an X in the stream?

            {} key - if yes
            {} key - if no
  thanks: Thank you for participating!
